'use client';

import { useEffect } from 'react';
import { animate, stagger } from 'animejs';
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';

export default function TermsPage() {
  useEffect(() => {
    animate('.terms-anim', {
      opacity: [0, 1],
      y: [20, 0],
      delay: stagger(50),
      duration: 1000,
      ease: 'outExpo'
    });
  }, []);

  const sections = [
    {
      title: '01. Acceptance of Terms',
      content: 'By creating an account on ORCA or accessing any part of the nexonic-industries.vercel.app platform, you agree to be bound by these Terms of Service. If you are using ORCA on behalf of an organisation, you represent that you have the authority to bind that organisation to these terms.'
    },
    {
      title: '02. Description of Service',
      content: 'ORCA is an AI Company OS provided by Nexonic Industries. The service includes access to AI executives across 5 departments, cross-department coordination tools, team management features, and access to the Nexonic ecosystem (CyberGuard, Render.AI, Intuition, The Summit, Island of Relevancy).'
    },
    {
      title: '03. Accounts and Registration',
      content: 'You must be at least 18 years old to create an account. You agree to provide accurate information and maintain account security. Each individual may only create one account; circumvention of plan limits via multiple accounts is a violation of these terms.'
    },
    {
      title: '04. Subscriptions and Billing',
      content: 'ORCA offers Free, Starter, and Growth (Pro) plans. All paid plans include a 14-day free trial. We use Paystack for payment processing. You may cancel at any time; cancellation takes effect at the end of your current billing period. We offer a full refund within 7 days of your first payment.'
    },
    {
      title: '05. Acceptable Use',
      content: 'You agree not to use ORCA for illegal activities, reverse engineering, generating spam/phishing content, or attempting to circumvent rate limits. Violation may result in immediate account termination without refund.'
    },
    {
      title: '06. AI-Generated Content',
      content: 'ORCA\'s agents generate content using LLMs. AI-generated content may contain errors. You are responsible for reviewing all agent outputs before using them externally. You own all content generated by ORCA agents on your behalf.'
    },
    {
      title: '07. Intellectual Property',
      content: 'You retain full ownership of all data you input. Nexonic Industries owns all intellectual property rights in the ORCA platform, including software, design, and coordination protocols.'
    },
    {
      title: '08. Data and Privacy',
      content: 'Your use of ORCA is governed by our Privacy Policy. We do not sell your data or use it to train AI models. Your company data remains yours.'
    },
    {
      title: '09. Third-Party Integrations',
      content: 'ORCA integrates with third-party services (GitHub, Slack, etc.). Your use of these is subject to their respective terms. Nexonic is not responsible for the conduct of third-party services.'
    },
    {
      title: '10. Limitation of Liability',
      content: 'Nexonic Industries is not liable for indirect, incidental, or consequential damages. Our total liability shall not exceed the amount you paid in the 3 months preceding the claim.'
    },
    {
      title: '11. Indemnification',
      content: 'You agree to indemnify Nexonic Industries from any claims or damages arising from your use of ORCA, your violation of these terms, or your violation of any third party\'s rights.'
    },
    {
      title: '12. Modifications to Terms',
      content: 'We may update these terms at any time. We will notify you of material changes 14 days before they take effect.'
    },
    {
      title: '13. Termination',
      content: 'You may terminate your account via Account settings. We may suspend or terminate your account for violations of these terms or fraudulent activity.'
    },
    {
      title: '14. Governing Law',
      content: 'These terms are governed by the laws of Kenya. Disputes shall be subject to the exclusive jurisdiction of the courts of Nairobi, Kenya.'
    },
    {
      title: '15. Contact',
      content: 'For questions about these terms, contact legal@nexonic.com or visit nexonic-industries.vercel.app.'
    }
  ];

  return (
    <main className="min-h-screen bg-bg text-text-body font-dm-mono overflow-x-hidden">
      <Navigation />
      
      <div className="max-w-4xl mx-auto px-6 py-40">
        <h1 className="terms-anim opacity-0 font-syne text-5xl sm:text-7xl lg:text-[100px] font-black text-white uppercase tracking-tighter mb-12 leading-none">
          Terms of <span className="text-green">Service</span>
        </h1>
        
        <div className="grid grid-cols-1 gap-12">
          {sections.map((section, idx) => (
            <section key={idx} className="terms-anim opacity-0 border-l border-white/5 pl-8 py-4 hover:border-green/20 transition-colors">
               <h2 className="font-syne text-xs font-black text-green uppercase tracking-[0.4em] mb-4 italic">
                 {section.title}
               </h2>
               <p className="text-white/40 font-dm-mono uppercase tracking-tighter font-black leading-relaxed text-sm">
                 {section.content}
               </p>
            </section>
          ))}
        </div>

        <section className="terms-anim opacity-0 mt-24 pt-12 border-t border-white/5 flex flex-col sm:flex-row justify-between items-center gap-6">
           <span className="text-[10px] text-white/20 font-black uppercase tracking-widest">
             LAST UPDATED: MARCH 2026 // NEXONIC INDUSTRIES LEGAL NODES
           </span>
           <span className="text-[10px] text-white/20 font-black uppercase tracking-widest">
             REF: BOS-KY-2026-TERMS
           </span>
        </section>
      </div>

      <Footer />
    </main>
  );
}

